### ISSUE TITLE
Add dependabot integration

### ISSUE THREAD

**Issue by S0obi** [derlin/rickroller#6]
Hey @derlin, thanks for this repo!

I feel like the cherry on the cake of this Github Action workflow will be the usage of Dependabot to upgrade project dependencies automatically.

Here is an example I found online for poetry: 

```yaml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
```

Reference : [Configuration options for the dependabot.yml file](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file)
